// <auto-generated />
using BD_Kurs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BD_Kurs.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241206224417_Final2")]
    partial class Final2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BD_Kurs.Det", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Mаrka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("T1")
                        .HasColumnType("int");

                    b.Property<double>("de1")
                        .HasColumnType("float");

                    b.Property<double>("m")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("BD_Kurs.Itog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DetId")
                        .HasColumnType("int");

                    b.Property<double>("de1")
                        .HasColumnType("float");

                    b.Property<double>("m")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("DetId")
                        .IsUnique();

                    b.ToTable("Itogi");
                });

            modelBuilder.Entity("BD_Kurs.Sborka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DetId")
                        .HasColumnType("int");

                    b.Property<string>("HB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Kbe")
                        .HasColumnType("float");

                    b.Property<int>("Kd")
                        .HasColumnType("int");

                    b.Property<double>("Kfb")
                        .HasColumnType("float");

                    b.Property<double>("Khb")
                        .HasColumnType("float");

                    b.Property<double>("Khl")
                        .HasColumnType("float");

                    b.Property<double>("Km")
                        .HasColumnType("float");

                    b.Property<string>("Mater")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOpor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypePer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.Property<double>("thi")
                        .HasColumnType("float");

                    b.Property<double>("thiHP")
                        .HasColumnType("float");

                    b.Property<double>("u")
                        .HasColumnType("float");

                    b.Property<double>("x")
                        .HasColumnType("float");

                    b.Property<double>("z")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("DetId")
                        .IsUnique();

                    b.ToTable("Sborki");
                });

            modelBuilder.Entity("BD_Kurs.Itog", b =>
                {
                    b.HasOne("BD_Kurs.Det", "Det")
                        .WithOne("Itog")
                        .HasForeignKey("BD_Kurs.Itog", "DetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Det");
                });

            modelBuilder.Entity("BD_Kurs.Sborka", b =>
                {
                    b.HasOne("BD_Kurs.Det", "Det")
                        .WithOne("Sborka")
                        .HasForeignKey("BD_Kurs.Sborka", "DetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Det");
                });

            modelBuilder.Entity("BD_Kurs.Det", b =>
                {
                    b.Navigation("Itog")
                        .IsRequired();

                    b.Navigation("Sborka")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
